### ISSUE TITLE
2020-27 Metadata standard version - XML example incorrect (Graham Parton, NCAS, November 2020)

### ISSUE THREAD

**Issue by PeterParslow** [agiorguk/gemini#14]
Graham points out that the XML examples we give for elements 54 & 55 are inconsistent with each other. The example for 55 
<gmx:Anchor xlink:href="http://vocab.nerc.ac.uk/collection/M25/current/GEMINI/">ISO 19115 (GEMINI)</gmx:Anchor>
Proposed solution (Peter): Should use “UK GEMINI” as the textual content of the anchor

**Comment by archaeogeek** [comment]
This is important for implementations using GeoNetwork (and specifically the Gemini 2.3 plugin) as this element is used for GeoNetwork to "recognise" the metadata as Gemini 2.3 and hence display it using the correct configuration files. See https://github.com/metadata101/iso19139.gemini23/blob/3.10.x/src/main/plugin/iso19139.gemini23/schema-ident.xml#L38-L47. 
If it is not correct, then GeoNetwork will probably recognise the metadata as ISO19139, but will use the default configuration files and validation schematron rather than the Gemini-specific ones.

If there's a strong preference for a different `metadataStandardName` then the entry in `autodetect` linked to above could be changed, but we'd be relying on all implementations of the plugin to update their code.

**Comment by PeterParslow** [comment]
2021-06-08: fix this

**Comment by PeterParslow** [comment]
Fixed locally (i.e. on my laptop, in GEMINI_20210629.xml)

**Comment by PeterParslow** [comment]
Fixed during migration to GitHub publication
