### ISSUE TITLE
conformity report for Implementing Rule 1089/2010, where conformance is not evaluated.

### ISSUE THREAD

**Issue by coalsh** [agiorguk/gemini#142]
I was looking at the conformity guidance around Commission Regulation (EU) No 1089/2010. The guidance notes state: _For INSPIRE, Datasets and dataset series shall declare conformity to [Regulation 1089/2010]_ and the guidance notes has an XML example where Implementing Rule 1089/2010 conformance is not evaluated (example 2):

https://agiorguk.github.io/gemini/1062-gemini-datasets-and-data-series.html#41
 
In the XML, if a metadata author sets **gmd:pass** to **gco:nilReason='unknown'** and **gmd:explanation** to **gco:nilReason='inapplicable'** because the conformance for Commission Regulation (EU) No 1089/2010 has not been evaluated (as seen in the second  XML example) , does that count as an official declaration of conformity to INSPIRE Regulation 1089/2010? Or does **gmd:pass** need to have a true or false Boolean value and subsequent explanation to be a declaration?
 
To me, it looks like specifying that Commission Regulation (EU) No 1089/2010 has not been evaluated is not a declaration of conformity to that specification and as a consequence, is not fulfilling this INSPIRE requirement?

**Comment by nmtoken** [comment]
> does that count as an official declaration of conformity to INSPIRE Regulation 1089/2010?

Yes

The INSPIRE metadata guidance was changed explicitly to allow this when conformance hasn't been tested, instead of the previous guidance to make declaration of false (which was seen as ambiguous, as it could meen not evaluated, or it could mean has been evaluated and is not conformant).

See TG Requirement C.22: metadata/2.0/req/common/conformity-degree from Version 2.0.1 of Technical Guidance for INSPIRE metadata for datasets and services

**Comment by coalsh** [comment]
Hi James, thank you for confirming and for responding so quickly. Very much appreciated.
