### ISSUE TITLE
Do GEMINI follow INSPIRE TG Requirement C.15 on giving 'publication' date for originating controlled vocabulary?

### ISSUE THREAD

**Issue by Sgaff** [agiorguk/gemini#69]
MEDIN have identified a potential discrepancy between the INSPIRE TG documentation and the GEMINI guidance for keywords.

The INSPIRE TG requirement is 

TG Requirement C.15: metadata/2.0/req/common/keyword-originating-cv 
When using keywords originating from a controlled vocabulary, the originating controlled vocabulary shall be cited using gmd:descriptiveKeywords/gmd:MD_Keywords/gmd:thesaurusName/gmd:CI_Citation element. 
The title of the vocabulary shall be given using gmd:title element with a Non-empty Free Text Element content. 
The **publication date of the vocabulary shall be given** using the gmd:date/gmd:CI_Date/gmd:date/gco:Date and gmd:dateType/gmd:CI_DateTypeCode24 elements.

whereas GEMINI don't state publication date as a requirement, but simply ask for a reference data as one of creation, revision or publication.

MEDIN would like this clarified as we use the NERC Vocab Server which is continually updated and revised and therefore any dates from keywords from the NVS will be date of last revision, not publication date. 

Are GEMINI being too loose, or is this an excessively tight requirement from INSPIRE that they would be happy to, in practice, see loosened to creation, revision or publication?

Thanks

Sean

**Comment by PeterParslow** [comment]
GEMINI _Keyword_ element Guidance currently says "The formal citation for the vocabulary should be given, including at least the title and reference date"

I agree this is looser than INSPIRE's metadata/2.0/req/common/keyword-originating-cv

But it does more nearly match the wording of the paragraph in the INSPIRE Metadata TG above that explicit requirement

"If the keyword value originates from a controlled vocabulary (thesaurus, ontology), for example GEMET, the citation of the originating controlled vocabulary shall be provided. This citation shall include at least the title and a reference date (date of publication, date of last revision or of creation) of the originating controlled vocabulary."

I think that is more useful to a user - what's the point of knowing when a particular controlled vocabulary was first published if it has been revised since?

I suggest we encourage INSPIRE to adjust their wording of the requirement.

**Comment by Sgaff** [comment]
I'd be very happy with that Peter, thanks

Sean

**Comment by PeterParslow** [comment]
@Sgaff : could you raise it as a new issue against the INSPIRE TG, at https://github.com/INSPIRE-MIF/technical-guidelines/issues? And then close it here.

**Comment by Sgaff** [comment]
Logged as https://github.com/INSPIRE-MIF/technical-guidelines/issues/18

**Comment by PeterParslow** [comment]
INSPIRE TG Requirement 15 (metadata/2.0/req/common/keyword-originating-cv) amended as we proposed, in August 2022
